### ISSUE TITLE
line 8: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by ghost** [furious-luke/lizards-are-awesome#3]
d@dVirtualBox:~$ bash laa init
/home/denis/.local/bin/laa: laa: line 8: syntax error near unexpected token `('
/home/denis/.local/bin/laa: laa: line 8: `def init(args):'

Please help. Cant seem to find the problem

**Comment by furious-luke** [comment]
Hi there,
The executable script `laa` is not actually a bash script, so running it under bash will generate that error. You should just be able to run the script without any prefix, i.e. `laa init`.
Cheers,
Luke

**Comment by ghost** [comment]
Hi Luke.Thanks for your swift reply.Let me start by saying im running xubuntu on virual box on my windows machine :-)This be the error im getting:VirtualBox:~/laa$ laa initdocker pull furiousluke/laa:latestWarning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/images/create?fromImage=furiousluke%2Flaa&tag=latest: dial unix /var/run/docker.sock: connect: permission deniedTraceback (most recent call last):  File "/usr/local/bin/laa", line 81, in <module>    args.func(args)  File "/usr/local/bin/laa", line 9, in init    laa.init()  File "/usr/local/lib/python2.7/dist-packages/laa/tasks.py", line 38, in init    local('docker pull {repo}'.format(**CONFIG))  File "/usr/local/lib/python2.7/dist-packages/laa/tasks.py", line 34, in local    subprocess.check_call(cmd, shell=True)  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call    raise CalledProcessError(retcode, cmd)subprocess.CalledProcessError: Command 'docker pull furiousluke/laa:latest' returned non-zero exit status 1
And before this i was getting;VirtualBox:~/shared$ laa init/home/denis/.local/bin/laa: line 1: fg: no job control/home/denis/.local/bin/laa: line 2: syntax error near unexpected token `ImageMagick'/home/denis/.local/bin/laa: line 2: `%%Creator: (ImageMagick)'
So what you think i should do?
CheersDenis 

    On Thursday, March 30, 2017 12:44 PM, Luke Hodkinson <notifications@github.com> wrote:
 

 Hi there,
The executable script laa is not actually a bash script, so running it under bash will generate that error. You should just be able to run the script without any prefix, i.e. laa init.
Cheers,
Luke—

**Comment by furious-luke** [comment]
Hmm, that looks to me like you may not have added yourself to the `docker` group during installation of Docker. Try running this:

```bash
usermod -aG docker ${USER}
```

and then restart your machine.

Cheers,
Luke

**Comment by furious-luke** [comment]
P.S. You may need to prefix that command with `sudo` then enter your password when prompted.

**Comment by ghost** [comment]
Hello Luke, Im still having the same problem even after adding myself to
the docker group.



dmm@dubuntu:~/Documents/biounix$ laa all data.csv --maxk=5 pdata
docker run -u 1000:1000 -it --rm -v /mnt/hgfs/biounix:/usr/local/app
furiousluke/laa:latest python /usr/local/bin/convert.py -m -c data.csv -o
data.ped
docker: Got permission denied while trying to connect to the Docker daemon
socket at unix:///var/run/docker.sock: Post
http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/create:
dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Traceback (most recent call last):
  File "/home/dmm/.local/bin/laa", line 81, in <module>
    args.func(args)
  File "/home/dmm/.local/bin/laa", line 33, in all
    laa.all(args.input[0], args.maxk)
  File "/home/dmm/.local/lib/python2.7/site-packages/laa/tasks.py", line
86, in all
    convert(input, conv_output + '.ped', **kwargs)
  File "/home/dmm/.local/lib/python2.7/site-packages/laa/tasks.py", line
56, in convert
    local(cmd)
  File "/home/dmm/.local/lib/python2.7/site-packages/laa/tasks.py", line
34, in local
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker run -u 1000:1000 -it --rm -v
/mnt/hgfs/biounix:/usr/local/app furiousluke/laa:latest python
/usr/local/bin/convert.py -m -c data.csv -o data.ped' returned non-zero
exit status 126

**Comment by furious-luke** [comment]
Well, the other possibility is that the docker daemon is not running. You can check it with `sudo service docker status`. If it's not running you should launch it with `sudo service docker start`.

Also, I'd highly recommend going over the docker installation guide again; these issues are due to an incorrectly installed docker. Take a look here: https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository

**Comment by ghost** [comment]
Hi Luke,I managed to install Docker CE and get it running on Xubuntu, and also get to use laa. Works like a charm :-) Thanks a lot for your help.Cheers
 

    On Tuesday, April 4, 2017 1:26 AM, Luke Hodkinson <notifications@github.com> wrote:
 

 Well, the other possibility is that the docker daemon is not running. You can check it with sudo service docker status. If it's not running you should launch it with sudo service docker start.Also, I'd highly recommend going over the docker installation guide again; these issues are due to an incorrectly installed docker. Take a look here: https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository—

**Comment by furious-luke** [comment]
You're welcome!
